# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\initial_setup_start.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_initialSetupStartWidget(object):
    def setupUi(self, initialSetupStartWidget):
        initialSetupStartWidget.setObjectName("initialSetupStartWidget")
        initialSetupStartWidget.resize(800, 480)
        initialSetupStartWidget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.logo = QtWidgets.QLabel(initialSetupStartWidget)
        self.logo.setGeometry(QtCore.QRect(215, 100, 370, 130))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/logo/icons/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.startButton = QtWidgets.QPushButton(initialSetupStartWidget)
        self.startButton.setGeometry(QtCore.QRect(277, 250, 246, 46))
        self.startButton.setStyleSheet("#startButton {\n"
"    background-color: rgb(242, 160, 160);\n"
"    font: 14pt \"나눔바른펜\";\n"
"    color: white;\n"
"    border-radius: 20%;\n"
"}")
        self.startButton.setObjectName("startButton")

        self.retranslateUi(initialSetupStartWidget)
        QtCore.QMetaObject.connectSlotsByName(initialSetupStartWidget)

    def retranslateUi(self, initialSetupStartWidget):
        _translate = QtCore.QCoreApplication.translate
        initialSetupStartWidget.setWindowTitle(_translate("initialSetupStartWidget", "Form"))
        self.startButton.setText(_translate("initialSetupStartWidget", "설정 시작하기"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    initialSetupStartWidget = QtWidgets.QWidget()
    ui = Ui_initialSetupStartWidget()
    ui.setupUi(initialSetupStartWidget)
    initialSetupStartWidget.show()
    sys.exit(app.exec_())
