# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\initial_setup_set_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_initialSetupSetPasswordWidget(object):
    def setupUi(self, initialSetupSetPasswordWidget):
        initialSetupSetPasswordWidget.setObjectName("initialSetupSetPasswordWidget")
        initialSetupSetPasswordWidget.resize(800, 480)
        font = QtGui.QFont()
        font.setFamily("나눔바른펜")
        initialSetupSetPasswordWidget.setFont(font)
        initialSetupSetPasswordWidget.setStyleSheet("background-color:white;")
        self.settingTextLabel = QtWidgets.QLabel(initialSetupSetPasswordWidget)
        self.settingTextLabel.setGeometry(QtCore.QRect(170, 50, 460, 91))
        self.settingTextLabel.setStyleSheet("#settingTextLabel {\n"
"font: 25pt \"나눔바른펜\";\n"
"\n"
"}")
        self.settingTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.settingTextLabel.setObjectName("settingTextLabel")
        self.passwordEdit = QtWidgets.QLineEdit(initialSetupSetPasswordWidget)
        self.passwordEdit.setGeometry(QtCore.QRect(170, 220, 460, 41))
        font = QtGui.QFont()
        font.setFamily("나눔바른펜")
        font.setPointSize(11)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setStyleSheet("#passwordEdit {\n"
"border: 1px solid #ddd;\n"
"}")
        self.passwordEdit.setInputMask("")
        self.passwordEdit.setText("")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setReadOnly(False)
        self.passwordEdit.setClearButtonEnabled(False)
        self.passwordEdit.setObjectName("passwordEdit")
        self.passwordReEdit = QtWidgets.QLineEdit(initialSetupSetPasswordWidget)
        self.passwordReEdit.setGeometry(QtCore.QRect(170, 280, 460, 41))
        font = QtGui.QFont()
        font.setFamily("나눔바른펜")
        font.setPointSize(11)
        self.passwordReEdit.setFont(font)
        self.passwordReEdit.setStyleSheet("#passwordReEdit {\n"
"border: 1px solid #ddd;\n"
"}")
        self.passwordReEdit.setInputMask("")
        self.passwordReEdit.setText("")
        self.passwordReEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordReEdit.setClearButtonEnabled(False)
        self.passwordReEdit.setObjectName("passwordReEdit")
        self.idEditReadOnly = QtWidgets.QLineEdit(initialSetupSetPasswordWidget)
        self.idEditReadOnly.setGeometry(QtCore.QRect(170, 160, 460, 41))
        font = QtGui.QFont()
        font.setFamily("나눔바른펜")
        font.setPointSize(11)
        self.idEditReadOnly.setFont(font)
        self.idEditReadOnly.setStyleSheet("#idEditReadOnly {\n"
"border: 1px solid #ddd;\n"
"}")
        self.idEditReadOnly.setInputMask("")
        self.idEditReadOnly.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.idEditReadOnly.setReadOnly(True)
        self.idEditReadOnly.setPlaceholderText("")
        self.idEditReadOnly.setClearButtonEnabled(False)
        self.idEditReadOnly.setObjectName("idEditReadOnly")
        self.settingButton = QtWidgets.QPushButton(initialSetupSetPasswordWidget)
        self.settingButton.setGeometry(QtCore.QRect(170, 340, 460, 41))
        font = QtGui.QFont()
        font.setFamily("나눔바른펜")
        font.setPointSize(12)
        self.settingButton.setFont(font)
        self.settingButton.setStyleSheet("#settingButton {\n"
"background-color:rgb(242, 160, 160);\n"
"color: white;\n"
"border: none;\n"
"}")
        self.settingButton.setObjectName("settingButton")

        self.retranslateUi(initialSetupSetPasswordWidget)
        QtCore.QMetaObject.connectSlotsByName(initialSetupSetPasswordWidget)

    def retranslateUi(self, initialSetupSetPasswordWidget):
        _translate = QtCore.QCoreApplication.translate
        initialSetupSetPasswordWidget.setWindowTitle(_translate("initialSetupSetPasswordWidget", "Form"))
        self.settingTextLabel.setText(_translate("initialSetupSetPasswordWidget", "에너지 지킴이 설정 - 1"))
        self.passwordEdit.setPlaceholderText(_translate("initialSetupSetPasswordWidget", "디바이스 비밀번호를 입력해주세요"))
        self.passwordReEdit.setPlaceholderText(_translate("initialSetupSetPasswordWidget", "디바이스 비밀번호를 다시 입력해주세요"))
        self.idEditReadOnly.setText(_translate("initialSetupSetPasswordWidget", "디바이스 아이디 : TEST_ID_INITIAL_2020_08_20"))
        self.settingButton.setText(_translate("initialSetupSetPasswordWidget", "비밀번호 설정"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    initialSetupSetPasswordWidget = QtWidgets.QWidget()
    ui = Ui_initialSetupSetPasswordWidget()
    ui.setupUi(initialSetupSetPasswordWidget)
    initialSetupSetPasswordWidget.show()
    sys.exit(app.exec_())
